CREATE DATABASE IF NOT EXISTS modular_erp;
USE modular_erp;

CREATE TABLE CUSTOMER (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(255) NOT NULL
);

CREATE TABLE CUSTOMER_PHONE_NO (
    Customer_ID INT,
    Phone_Number VARCHAR(20) NOT NULL,
    PRIMARY KEY (Customer_ID, Phone_Number),
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID) ON DELETE CASCADE
);

CREATE TABLE PRODUCT (
    Product_ID INT PRIMARY KEY,
    Product_Name VARCHAR(255) NOT NULL,
    Stock_Quantity INT NOT NULL DEFAULT 0,
    Price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE ORDERS (
    Order_ID INT PRIMARY KEY,
    Order_Date DATE NOT NULL,
    Customer_ID INT,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID) ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAILS (
    Order_ID INT,
    Product_ID INT,
    Quantity INT NOT NULL,
    PRIMARY KEY (Order_ID, Product_ID),
    FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID) ON DELETE CASCADE,
    FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID) ON DELETE CASCADE
);
